### ISSUE TITLE
audonnx not working with onnxruntime-gpu==1.10.0

### ISSUE THREAD

**Issue by ATriantafyllopoulos** [audeering/audonnx#14]
I recently tried running an `audonnx` model on the GPU, and installed the latest (`v1.10.0`) version for `onnxruntime-gpu`. Unfortunately model loading crashed with:
```bash
ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers par
ameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)
```

The issue was resolved after downgrading to `v1.9.0`. Judging by the error, I guess it's a simple instantiation problem of `InferenceSession`.

**Comment by ATriantafyllopoulos** [comment]
Apologies, I was not actually using the latest version of `audonnx` (I had `v0.9.3` or sth instead of `v0.5.0`). Now I use the latest versions of both packages and it seems to work (though it doesn't yet run on the GPU, but I expect I'll solve that).

I'll close this issue

**Comment by hagenw** [comment]
You have to specify the GPU (now as the `device` argument), compaere https://audeering.github.io/audonnx/usage.html#run-on-the-gpu

And it is indeed not that easy to implement `audonnx` to support a large variety of `onnxruntime` versions as they introduce quite big changes between releases.

But the last change we actually liked, because now you can finaly select the GPU directly from Python code (which was not possible before).
